// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHRC1THD-20ZgihHsO7IPjUIGLXQb_5EA',
    appId: '1:448840445828:web:11b47f55b608e78167f7d1',
    messagingSenderId: '448840445828',
    projectId: 'job-finder-app-578e2',
    authDomain: 'job-finder-app-578e2.firebaseapp.com',
    storageBucket: 'job-finder-app-578e2.appspot.com',
    measurementId: 'G-LX8FTS3RGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFOVJO7ooWoKF9kMpdXHgaiylmUVl1qN4',
    appId: '1:448840445828:android:69ea859cadb3104567f7d1',
    messagingSenderId: '448840445828',
    projectId: 'job-finder-app-578e2',
    storageBucket: 'job-finder-app-578e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD39WtupMwD5x-N1-SuM2elbASYQwDGLDQ',
    appId: '1:448840445828:ios:d984056fba7538f767f7d1',
    messagingSenderId: '448840445828',
    projectId: 'job-finder-app-578e2',
    storageBucket: 'job-finder-app-578e2.appspot.com',
    iosBundleId: 'com.example.jobFinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD39WtupMwD5x-N1-SuM2elbASYQwDGLDQ',
    appId: '1:448840445828:ios:d984056fba7538f767f7d1',
    messagingSenderId: '448840445828',
    projectId: 'job-finder-app-578e2',
    storageBucket: 'job-finder-app-578e2.appspot.com',
    iosBundleId: 'com.example.jobFinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHRC1THD-20ZgihHsO7IPjUIGLXQb_5EA',
    appId: '1:448840445828:web:d1a34c2b9bf6c92a67f7d1',
    messagingSenderId: '448840445828',
    projectId: 'job-finder-app-578e2',
    authDomain: 'job-finder-app-578e2.firebaseapp.com',
    storageBucket: 'job-finder-app-578e2.appspot.com',
    measurementId: 'G-LCW9326WVN',
  );
}
